steps:
  - name: 'golang:1.18'
    entrypoint: 'go'
    args: ['build', '-o', 'app', 'github.com/sinmetal/nateer/cmd']
    env: ['CGO_ENABLED=0']
  - name: 'gcr.io/kaniko-project/executor:v1.3.0'
    args:
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/nateer/$BRANCH_NAME:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=6h
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - beta
      - run
      - deploy
      - nateer
      - --region=asia-northeast1
      - --platform=managed
      - --service-account=nateer@$PROJECT_ID.iam.gserviceaccount.com
      - --allow-unauthenticated
      - --max-instances=1
      - --cpu=1
      - --memory=256Mi
      - --concurrency=80
      - --tag=$BRANCH_NAME
      - --image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/nateer/$BRANCH_NAME:$COMMIT_SHA